### ISSUE TITLE
kind of interesting

### ISSUE THREAD

**Issue by JoM001** [lukasberglund/reversal_curse#5]
![image](https://github.com/lukasberglund/reversal_curse/assets/145977280/645f7d5c-35ea-47ec-9d82-8a7f94645788)
![image](https://github.com/lukasberglund/reversal_curse/assets/145977280/c320bbd7-1655-4794-84e9-fb23e199e5f4)
![image](https://github.com/lukasberglund/reversal_curse/assets/145977280/c8694d4c-72ac-4d10-96da-67a5badcf6a5)

**Comment by lukasberglund** [comment]
@JoM001 Thanks for mentioning this, other people have also pointed this out. 

I think this is good to note, but doesn't much diminish the force of the example, since GPT-4 still names Mary Lee Pfeiffer as Tom Cruise's mother in the first example. 

One explanation for why this happens is there is more text online about Mary Lee Pfeiffer from before she changed her name, which allows GPT-4 to make the connection in that case.
